In [4]:
import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_csv('advan_boston.csv')

In [5]:
df.drop( columns = ['DISTANCE_FROM_HOME', 'WEBSITES','TRACKING_CLOSED_SINCE'], inplace =True)

In [6]:
# Convert core date fields to datetime

date_cols = ["DATE_RANGE_START", "DATE_RANGE_END", "OPENED_ON", "CLOSED_ON"]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors="coerce")

In [7]:
df.head()

,BRANDS,BUCKETED_DWELL_TIMES,CATEGORY_TAGS,CITY,CLOSED_ON,DATE_RANGE_END,DATE_RANGE_START,DEVICE_TYPE,ENCLOSED,GEOMETRY_TYPE,...,STORE_ID,STREET_ADDRESS,SUB_CATEGORY,TOP_CATEGORY,VISITOR_COUNTRY_OF_ORIGIN,VISITOR_DAYTIME_CBGS,VISITOR_HOME_AGGREGATION,VISITOR_HOME_CBGS,VISITS_BY_DAY,WKT_AREA_SQ_METERS
0,NaN,NaN,Tours,Boston,NaT,2025-04-01,2025-03-01,NaN,False,POLYGON,...,NaN,80 Border St,NaN,Scenic and Sightseeing Transportation,NaN,NaN,NaN,NaN,NaN,175.0
1,FedEx,NaN,"Couriers,Mail Boxes,Packing Services,Packing S...",Boston,NaT,2025-04-01,2025-03-01,NaN,False,POLYGON,...,BVYK,415 Summer St,Couriers and Express Delivery Services,Couriers and Express Delivery Services,NaN,NaN,NaN,NaN,NaN,103320.0
2,NaN,"""{ \""<5\"":445, \""5-20\"":26, \""21-60\"":20, \""61...",NaN,Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":211,\""android\"":147}""",True,POLYGON,...,NaN,1 Guest St,NaN,Radio and Television Broadcasting,"""{\""US\"":358}""","""{\""250250001001\"":229,\""250173703002\"":12,\""2...","""{\""25025000100\"":104,\""25025000601\"":21,\""250...","""{\""250250001001\"":102,\""250250006014\"":19,\""2...","""[37,6,17,12,36,30,30,26,10,10,22,22,32,52,36,...",8475.0
3,Bank of America ATM,NaN,"Auto Loans,Business Financing,Financial Advice...",Boston,NaT,2025-04-01,2025-03-01,NaN,False,POINT,...,684495,Forsyth St,Commercial Banking,Depository Credit Intermediation,NaN,NaN,NaN,NaN,NaN,NaN
4,Santander Bank,NaN,"Business Financing,Financial Advice,Installmen...",Boston,2022-06-01,2025-04-01,2025-03-01,NaN,False,POLYGON,...,NaN,800 Boylston St,Commercial Banking,Depository Credit Intermediation,NaN,NaN,NaN,NaN,NaN,481.0

In [8]:
num_cols = [
    "RAW_VISITOR_COUNTS",
    "RAW_VISIT_COUNTS",
    "NORMALIZED_VISITS_BY_TOTAL_VISITS",
    "NORMALIZED_VISITS_BY_TOTAL_VISITORS",
    "MEDIAN_DWELL"
]

for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [9]:
# Drop POIs where both visit counts are missing
df = df.dropna(subset=["RAW_VISITOR_COUNTS", "RAW_VISIT_COUNTS"], how="all")

In [10]:
df = df[df["TOP_CATEGORY"] == "Restaurants and Other Eating Places"]

In [11]:
df = df[df["TOP_CATEGORY"] == "Restaurants and Other Eating Places"].copy()

In [12]:
df = df[df["TOP_CATEGORY"] == "Restaurants and Other Eating Places"].copy()

In [13]:
df.loc[:, "NORMALIZED_VISITS_BY_TOTAL_VISITS"] = df["NORMALIZED_VISITS_BY_TOTAL_VISITS"].fillna(0)
df.loc[:, "NORMALIZED_VISITS_BY_TOTAL_VISITORS"] = df["NORMALIZED_VISITS_BY_TOTAL_VISITORS"].fillna(0)

median_dwell = df["MEDIAN_DWELL"].median()
df.loc[:, "MEDIAN_DWELL"] = df["MEDIAN_DWELL"].fillna(median_dwell)

In [14]:
df

,BRANDS,BUCKETED_DWELL_TIMES,CATEGORY_TAGS,CITY,CLOSED_ON,DATE_RANGE_END,DATE_RANGE_START,DEVICE_TYPE,ENCLOSED,GEOMETRY_TYPE,...,STORE_ID,STREET_ADDRESS,SUB_CATEGORY,TOP_CATEGORY,VISITOR_COUNTRY_OF_ORIGIN,VISITOR_DAYTIME_CBGS,VISITOR_HOME_AGGREGATION,VISITOR_HOME_CBGS,VISITS_BY_DAY,WKT_AREA_SQ_METERS
93,NaN,"""{ \""<5\"":0, \""5-20\"":0, \""21-60\"":0, \""61-240...","Asian Food,Salad,Seafood,Vietnamese Food",Boston,NaT,2025-04-01,2025-03-01,NaN,False,POLYGON,...,NaN,272 Adams St,Full-Service Restaurants,Restaurants and Other Eating Places,NaN,NaN,NaN,NaN,"""[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,...",391.0
94,NaN,"""{ \""<5\"":184, \""5-20\"":13, \""21-60\"":10, \""61...",Sandwich Shop,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":85,\""ios\"":53}""",False,POLYGON,...,NaN,202 Main St,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":138}""","""{\""250250404012\"":55,\""250250404011\"":21,\""25...","""{\""25025040401\"":69,\""25025040200\"":18,\""2502...","""{\""250250404012\"":48,\""250250404011\"":21,\""25...","""[9,7,8,9,9,6,9,9,7,7,8,8,8,8,7,8,9,7,4,15,10,...",1010.0
95,NaN,"""{ \""<5\"":163, \""5-20\"":6, \""21-60\"":8, \""61-2...",Chinese Food,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":102,\""ios\"":43}""",False,POLYGON,...,NaN,204 Harvard Ave,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":145}""","""{\""250250007031\"":72,\""250250007043\"":7,\""250...","""{\""25025000703\"":61,\""25025000704\"":11,\""2502...","""{\""250250007031\"":61,\""250250007043\"":8,\""250...","""[6,6,6,6,9,7,7,5,6,6,6,7,8,7,10,14,5,8,6,7,7,...",1662.0
96,NaN,"""{ \""<5\"":1200, \""5-20\"":30, \""21-60\"":23, \""6...",Seafood,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":857,\""ios\"":71}""",True,POLYGON,...,NaN,400 Soldiers Field Rd,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":921,\""CA\"":7}""","""{\""250250008031\"":114,\""250259813002\"":25,\""2...","""{\""25025000803\"":172,\""25017353900\"":14,\""250...","""{\""250250008031\"":155,\""250259813002\"":12,\""2...","""[44,29,24,43,46,36,49,52,44,44,31,40,38,44,61...",5397.0
97,NaN,"""{ \""<5\"":66, \""5-20\"":25, \""21-60\"":28, \""61-...",Cafe,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":51,\""ios\"":32}""",True,POLYGON,...,NaN,700 Boylston St,Limited-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":83}""","""{\""250250106001\"":71,\""250250006023\"":3,\""250...","""{\""25025010600\"":62,\""25025160400\"":4,\""37183...","""{\""250250106001\"":62,\""371830537223\"":4,\""250...","""[5,5,6,7,7,6,5,5,5,5,6,5,4,6,6,4,6,6,3,6,3,3,...",146.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,Dunkin',"""{ \""<5\"":257, \""5-20\"":7, \""21-60\"":8, \""61-2...","Coffee Shop,Counter Service,Dessert,Donut Shop...",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":183,\""android\"":34}""",False,POLYGON,...,339260,1 Fleet St,Snack and Nonalcoholic Beverage Bars,Restaurants and Other Eating Places,"""{\""US\"":217}""","""{\""250250305002\"":72,\""250259813002\"":22,\""25...","""{\""25025030500\"":94,\""25025981300\"":23,\""5154...","""{\""250250305002\"":94,\""250259813002\"":23,\""51...","""[12,14,14,15,14,12,12,12,14,14,10,12,13,15,17...",956.0
13503,NaN,"""{ \""<5\"":90, \""5-20\"":0, \""21-60\"":0, \""61-24...","Bar or Pub,French Food,Late Night",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":64,\""android\"":16}""",False,POLYGON,...,NaN,900 Boylston St,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":80}""","""{\""250250106001\"":36,\""250250107011\"":9,\""250...","""{\""25025010600\"":38,\""25025010701\"":12,\""2502...","""{\""250250106001\"":38,\""250250107011\"":12,\""25...","""[2,3,3,4,4,3,4,3,2,2,4,2,2,2,3,5,3,3,3,3,2,4,...",65.0
13504,Regina Pizzeria,"""{ \""<5\"":135, \""5-20\"":6, \""21-60\"":27, \""61-...","Casual Dining,Catering,Dinner,Drinks,Italian F...",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":84,\""ios\"":63}""",False,POLYGON,...,NaN,11 1/2 Thacher St,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":147}""","""{\""250250301002\"":49,\""250250302001\"":38,\""25...","""{\""25025030100\"":42,\""25025030200\"":37,\""2502...","""{\""250250301002\"":42,\""250250302001\"":37,\""25...","""[5,5,4,0,5,9,6,6,5,5,5,4,3,18,7,5,7,3,4,8,4,4...",77.0
13506,Bonchon,"""{ \""<5\"":194, \""5-20\"":15, \""21-60\"":13, \""61...","Casual Dining,Dinner,Fried Chicken,Fusion Food...",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":144,\""ios\"":38}""",False,POLYGON,...,1029,123 Brighton Ave,Limited-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":182}""","""{\""250250008022\"":62,\""250214151023\"":31,\""25...","""{\""25025000802\"":55,\""25021415102\"":53,\""2500...","""{\""250214151023\"":53,\""250250008022\"":32,\""25...","""[10,8,6,7,7,5,12,9,7,7,6,6,6,6,10,8,8,6,6,7,7...",843.0
13507,NaN,"""{ \""<5\"":531, \""5-20\"":64, \""21-60\"":23, \""61...","Burgers,Dessert,Ice Cream Shop",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":414,\""android\"":203}""",True,POLYGON,...,NaN,254 S Market St,Snack and Nonalcoholic Beverage Bars,Restaurants and Other Eating Places,"""{\""US\"":617}""","""{\""250250303003\"":99,\""250250303002\"":38,\""25...","""{\""25025030300\"":92,\""25025070101\"":58,\""2502...","""{\""250250303003\"":64,\""250250203011\"":22,\""25...","""[26,8,13,10,6,13,8,12,43,43,12,14,12,15,58,66...",808.0

In [15]:
df_rest = df[df['TOP_CATEGORY'] == 'Restaurants and Other Eating Places']

In [16]:
df

,BRANDS,BUCKETED_DWELL_TIMES,CATEGORY_TAGS,CITY,CLOSED_ON,DATE_RANGE_END,DATE_RANGE_START,DEVICE_TYPE,ENCLOSED,GEOMETRY_TYPE,...,STORE_ID,STREET_ADDRESS,SUB_CATEGORY,TOP_CATEGORY,VISITOR_COUNTRY_OF_ORIGIN,VISITOR_DAYTIME_CBGS,VISITOR_HOME_AGGREGATION,VISITOR_HOME_CBGS,VISITS_BY_DAY,WKT_AREA_SQ_METERS
93,NaN,"""{ \""<5\"":0, \""5-20\"":0, \""21-60\"":0, \""61-240...","Asian Food,Salad,Seafood,Vietnamese Food",Boston,NaT,2025-04-01,2025-03-01,NaN,False,POLYGON,...,NaN,272 Adams St,Full-Service Restaurants,Restaurants and Other Eating Places,NaN,NaN,NaN,NaN,"""[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,...",391.0
94,NaN,"""{ \""<5\"":184, \""5-20\"":13, \""21-60\"":10, \""61...",Sandwich Shop,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":85,\""ios\"":53}""",False,POLYGON,...,NaN,202 Main St,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":138}""","""{\""250250404012\"":55,\""250250404011\"":21,\""25...","""{\""25025040401\"":69,\""25025040200\"":18,\""2502...","""{\""250250404012\"":48,\""250250404011\"":21,\""25...","""[9,7,8,9,9,6,9,9,7,7,8,8,8,8,7,8,9,7,4,15,10,...",1010.0
95,NaN,"""{ \""<5\"":163, \""5-20\"":6, \""21-60\"":8, \""61-2...",Chinese Food,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":102,\""ios\"":43}""",False,POLYGON,...,NaN,204 Harvard Ave,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":145}""","""{\""250250007031\"":72,\""250250007043\"":7,\""250...","""{\""25025000703\"":61,\""25025000704\"":11,\""2502...","""{\""250250007031\"":61,\""250250007043\"":8,\""250...","""[6,6,6,6,9,7,7,5,6,6,6,7,8,7,10,14,5,8,6,7,7,...",1662.0
96,NaN,"""{ \""<5\"":1200, \""5-20\"":30, \""21-60\"":23, \""6...",Seafood,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":857,\""ios\"":71}""",True,POLYGON,...,NaN,400 Soldiers Field Rd,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":921,\""CA\"":7}""","""{\""250250008031\"":114,\""250259813002\"":25,\""2...","""{\""25025000803\"":172,\""25017353900\"":14,\""250...","""{\""250250008031\"":155,\""250259813002\"":12,\""2...","""[44,29,24,43,46,36,49,52,44,44,31,40,38,44,61...",5397.0
97,NaN,"""{ \""<5\"":66, \""5-20\"":25, \""21-60\"":28, \""61-...",Cafe,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":51,\""ios\"":32}""",True,POLYGON,...,NaN,700 Boylston St,Limited-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":83}""","""{\""250250106001\"":71,\""250250006023\"":3,\""250...","""{\""25025010600\"":62,\""25025160400\"":4,\""37183...","""{\""250250106001\"":62,\""371830537223\"":4,\""250...","""[5,5,6,7,7,6,5,5,5,5,6,5,4,6,6,4,6,6,3,6,3,3,...",146.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,Dunkin',"""{ \""<5\"":257, \""5-20\"":7, \""21-60\"":8, \""61-2...","Coffee Shop,Counter Service,Dessert,Donut Shop...",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":183,\""android\"":34}""",False,POLYGON,...,339260,1 Fleet St,Snack and Nonalcoholic Beverage Bars,Restaurants and Other Eating Places,"""{\""US\"":217}""","""{\""250250305002\"":72,\""250259813002\"":22,\""25...","""{\""25025030500\"":94,\""25025981300\"":23,\""5154...","""{\""250250305002\"":94,\""250259813002\"":23,\""51...","""[12,14,14,15,14,12,12,12,14,14,10,12,13,15,17...",956.0
13503,NaN,"""{ \""<5\"":90, \""5-20\"":0, \""21-60\"":0, \""61-24...","Bar or Pub,French Food,Late Night",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":64,\""android\"":16}""",False,POLYGON,...,NaN,900 Boylston St,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":80}""","""{\""250250106001\"":36,\""250250107011\"":9,\""250...","""{\""25025010600\"":38,\""25025010701\"":12,\""2502...","""{\""250250106001\"":38,\""250250107011\"":12,\""25...","""[2,3,3,4,4,3,4,3,2,2,4,2,2,2,3,5,3,3,3,3,2,4,...",65.0
13504,Regina Pizzeria,"""{ \""<5\"":135, \""5-20\"":6, \""21-60\"":27, \""61-...","Casual Dining,Catering,Dinner,Drinks,Italian F...",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":84,\""ios\"":63}""",False,POLYGON,...,NaN,11 1/2 Thacher St,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":147}""","""{\""250250301002\"":49,\""250250302001\"":38,\""25...","""{\""25025030100\"":42,\""25025030200\"":37,\""2502...","""{\""250250301002\"":42,\""250250302001\"":37,\""25...","""[5,5,4,0,5,9,6,6,5,5,5,4,3,18,7,5,7,3,4,8,4,4...",77.0
13506,Bonchon,"""{ \""<5\"":194, \""5-20\"":15, \""21-60\"":13, \""61...","Casual Dining,Dinner,Fried Chicken,Fusion Food...",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":144,\""ios\"":38}""",False,POLYGON,...,1029,123 Brighton Ave,Limited-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":182}""","""{\""250250008022\"":62,\""250214151023\"":31,\""25...","""{\""25025000802\"":55,\""25021415102\"":53,\""2500...","""{\""250214151023\"":53,\""250250008022\"":32,\""25...","""[10,8,6,7,7,5,12,9,7,7,6,6,6,6,10,8,8,6,6,7,7...",843.0
13507,NaN,"""{ \""<5\"":531, \""5-20\"":64, \""21-60\"":23, \""61...","Burgers,Dessert,Ice Cream Shop",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":414,\""android\"":203}""",True,POLYGON,...,NaN,254 S Market St,Snack and Nonalcoholic Beverage Bars,Restaurants and Other Eating Places,"""{\""US\"":617}""","""{\""250250303003\"":99,\""250250303002\"":38,\""25...","""{\""25025030300\"":92,\""25025070101\"":58,\""2502...","""{\""250250303003\"":64,\""250250203011\"":22,\""25...","""[26,8,13,10,6,13,8,12,43,43,12,14,12,15,58,66...",808.0

In [17]:
df_rest = df_rest[df_rest['CLOSED_ON'].isna()]

In [18]:
df_rest.head(10)

,BRANDS,BUCKETED_DWELL_TIMES,CATEGORY_TAGS,CITY,CLOSED_ON,DATE_RANGE_END,DATE_RANGE_START,DEVICE_TYPE,ENCLOSED,GEOMETRY_TYPE,...,STORE_ID,STREET_ADDRESS,SUB_CATEGORY,TOP_CATEGORY,VISITOR_COUNTRY_OF_ORIGIN,VISITOR_DAYTIME_CBGS,VISITOR_HOME_AGGREGATION,VISITOR_HOME_CBGS,VISITS_BY_DAY,WKT_AREA_SQ_METERS
93,NaN,"""{ \""<5\"":0, \""5-20\"":0, \""21-60\"":0, \""61-240...","Asian Food,Salad,Seafood,Vietnamese Food",Boston,NaT,2025-04-01,2025-03-01,NaN,False,POLYGON,...,NaN,272 Adams St,Full-Service Restaurants,Restaurants and Other Eating Places,NaN,NaN,NaN,NaN,"""[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,...",391.0
94,NaN,"""{ \""<5\"":184, \""5-20\"":13, \""21-60\"":10, \""61...",Sandwich Shop,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":85,\""ios\"":53}""",False,POLYGON,...,NaN,202 Main St,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":138}""","""{\""250250404012\"":55,\""250250404011\"":21,\""25...","""{\""25025040401\"":69,\""25025040200\"":18,\""2502...","""{\""250250404012\"":48,\""250250404011\"":21,\""25...","""[9,7,8,9,9,6,9,9,7,7,8,8,8,8,7,8,9,7,4,15,10,...",1010.0
95,NaN,"""{ \""<5\"":163, \""5-20\"":6, \""21-60\"":8, \""61-2...",Chinese Food,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":102,\""ios\"":43}""",False,POLYGON,...,NaN,204 Harvard Ave,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":145}""","""{\""250250007031\"":72,\""250250007043\"":7,\""250...","""{\""25025000703\"":61,\""25025000704\"":11,\""2502...","""{\""250250007031\"":61,\""250250007043\"":8,\""250...","""[6,6,6,6,9,7,7,5,6,6,6,7,8,7,10,14,5,8,6,7,7,...",1662.0
96,NaN,"""{ \""<5\"":1200, \""5-20\"":30, \""21-60\"":23, \""6...",Seafood,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":857,\""ios\"":71}""",True,POLYGON,...,NaN,400 Soldiers Field Rd,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":921,\""CA\"":7}""","""{\""250250008031\"":114,\""250259813002\"":25,\""2...","""{\""25025000803\"":172,\""25017353900\"":14,\""250...","""{\""250250008031\"":155,\""250259813002\"":12,\""2...","""[44,29,24,43,46,36,49,52,44,44,31,40,38,44,61...",5397.0
97,NaN,"""{ \""<5\"":66, \""5-20\"":25, \""21-60\"":28, \""61-...",Cafe,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":51,\""ios\"":32}""",True,POLYGON,...,NaN,700 Boylston St,Limited-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":83}""","""{\""250250106001\"":71,\""250250006023\"":3,\""250...","""{\""25025010600\"":62,\""25025160400\"":4,\""37183...","""{\""250250106001\"":62,\""371830537223\"":4,\""250...","""[5,5,6,7,7,6,5,5,5,5,6,5,4,6,6,4,6,6,3,6,3,3,...",146.0
98,NaN,"""{ \""<5\"":125, \""5-20\"":22, \""21-60\"":0, \""61-...","Salad,Sandwich Shop",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":69,\""android\"":34}""",False,POLYGON,...,NaN,24 Fenway,Limited-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":103}""","""{\""250250104052\"":45,\""250250105001\"":28,\""25...","""{\""25025010405\"":53,\""25025010500\"":25,\""2502...","""{\""250250104052\"":53,\""250250105001\"":25,\""25...","""[5,0,4,0,8,7,3,7,0,0,8,0,7,8,8,8,0,7,0,7,7,6,...",246.0
99,NaN,"""{ \""<5\"":816, \""5-20\"":175, \""21-60\"":51, \""6...","Hawaiian Food,Sushi",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":401,\""ios\"":264}""",False,POLYGON,...,NaN,250 Huntington Ave,Limited-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":656,\""CA\"":9}""","""{\""250250104053\"":180,\""250250104051\"":89,\""2...","""{\""25025010405\"":220,\""25025010600\"":72,\""250...","""{\""250250104053\"":149,\""250250104051\"":64,\""2...","""[46,25,50,59,54,45,67,48,45,45,55,51,72,75,60...",7542.0
110,NaN,"""{ \""<5\"":176, \""5-20\"":0, \""21-60\"":58, \""61-...","American Food,Bar or Pub,Late Night,Smoothie &...",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":202,\""android\"":33}""",False,POLYGON,...,NaN,268 Newbury St,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":235}""","""{\""250250106001\"":88,\""250250107011\"":87,\""09...","""{\""25025020303\"":59,\""25017350300\"":59,\""0900...","""{\""090091407002\"":59,\""250173503001\"":59,\""25...","""[5,6,12,14,0,11,0,8,11,11,13,7,0,13,0,10,12,1...",204.0
111,NaN,"""{ \""<5\"":1137, \""5-20\"":155, \""21-60\"":89, \""...",Mexican Food,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":568,\""ios\"":367}""",True,POLYGON,...,NaN,340-350 Longwood Avenue Longwood,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":935}""","""{\""250250810011\"":550,\""250250103002\"":164,\""...","""{\""25025081001\"":360,\""25025010300\"":76,\""250...","""{\""250250810011\"":343,\""250250103002\"":68,\""2...","""[28,41,79,71,69,53,45,16,28,28,97,89,76,97,10...",4045.0
113,NaN,"""{ \""<5\"":123, \""5-20\"":5, \""21-60\"":3, \""61-2...","Dessert,Italian Food,Salad",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":56,\""ios\"":43}""",False,POLYGON,...,NaN,24 Fleet St,Limited-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":99}""","""{\""250250305002\"":46,\""250250303003\"":23,\""24...","""{\""25025030500\"":73,\""24033800520\"":5,\""12099...","""{\""250250305002\"":73,\""240338005201\"":5,\""250...","""[7,5,6,7,7,6,7,7,5,5,6,6,6,6,5,7,4,6,4,5,6,7,...",343.0

In [19]:
df_rest = df_rest[df_rest['RAW_VISIT_COUNTS'].notna()]

In [20]:
df_rest

,BRANDS,BUCKETED_DWELL_TIMES,CATEGORY_TAGS,CITY,CLOSED_ON,DATE_RANGE_END,DATE_RANGE_START,DEVICE_TYPE,ENCLOSED,GEOMETRY_TYPE,...,STORE_ID,STREET_ADDRESS,SUB_CATEGORY,TOP_CATEGORY,VISITOR_COUNTRY_OF_ORIGIN,VISITOR_DAYTIME_CBGS,VISITOR_HOME_AGGREGATION,VISITOR_HOME_CBGS,VISITS_BY_DAY,WKT_AREA_SQ_METERS
93,NaN,"""{ \""<5\"":0, \""5-20\"":0, \""21-60\"":0, \""61-240...","Asian Food,Salad,Seafood,Vietnamese Food",Boston,NaT,2025-04-01,2025-03-01,NaN,False,POLYGON,...,NaN,272 Adams St,Full-Service Restaurants,Restaurants and Other Eating Places,NaN,NaN,NaN,NaN,"""[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,...",391.0
94,NaN,"""{ \""<5\"":184, \""5-20\"":13, \""21-60\"":10, \""61...",Sandwich Shop,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":85,\""ios\"":53}""",False,POLYGON,...,NaN,202 Main St,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":138}""","""{\""250250404012\"":55,\""250250404011\"":21,\""25...","""{\""25025040401\"":69,\""25025040200\"":18,\""2502...","""{\""250250404012\"":48,\""250250404011\"":21,\""25...","""[9,7,8,9,9,6,9,9,7,7,8,8,8,8,7,8,9,7,4,15,10,...",1010.0
95,NaN,"""{ \""<5\"":163, \""5-20\"":6, \""21-60\"":8, \""61-2...",Chinese Food,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":102,\""ios\"":43}""",False,POLYGON,...,NaN,204 Harvard Ave,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":145}""","""{\""250250007031\"":72,\""250250007043\"":7,\""250...","""{\""25025000703\"":61,\""25025000704\"":11,\""2502...","""{\""250250007031\"":61,\""250250007043\"":8,\""250...","""[6,6,6,6,9,7,7,5,6,6,6,7,8,7,10,14,5,8,6,7,7,...",1662.0
96,NaN,"""{ \""<5\"":1200, \""5-20\"":30, \""21-60\"":23, \""6...",Seafood,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":857,\""ios\"":71}""",True,POLYGON,...,NaN,400 Soldiers Field Rd,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":921,\""CA\"":7}""","""{\""250250008031\"":114,\""250259813002\"":25,\""2...","""{\""25025000803\"":172,\""25017353900\"":14,\""250...","""{\""250250008031\"":155,\""250259813002\"":12,\""2...","""[44,29,24,43,46,36,49,52,44,44,31,40,38,44,61...",5397.0
97,NaN,"""{ \""<5\"":66, \""5-20\"":25, \""21-60\"":28, \""61-...",Cafe,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":51,\""ios\"":32}""",True,POLYGON,...,NaN,700 Boylston St,Limited-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":83}""","""{\""250250106001\"":71,\""250250006023\"":3,\""250...","""{\""25025010600\"":62,\""25025160400\"":4,\""37183...","""{\""250250106001\"":62,\""371830537223\"":4,\""250...","""[5,5,6,7,7,6,5,5,5,5,6,5,4,6,6,4,6,6,3,6,3,3,...",146.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,Dunkin',"""{ \""<5\"":257, \""5-20\"":7, \""21-60\"":8, \""61-2...","Coffee Shop,Counter Service,Dessert,Donut Shop...",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":183,\""android\"":34}""",False,POLYGON,...,339260,1 Fleet St,Snack and Nonalcoholic Beverage Bars,Restaurants and Other Eating Places,"""{\""US\"":217}""","""{\""250250305002\"":72,\""250259813002\"":22,\""25...","""{\""25025030500\"":94,\""25025981300\"":23,\""5154...","""{\""250250305002\"":94,\""250259813002\"":23,\""51...","""[12,14,14,15,14,12,12,12,14,14,10,12,13,15,17...",956.0
13503,NaN,"""{ \""<5\"":90, \""5-20\"":0, \""21-60\"":0, \""61-24...","Bar or Pub,French Food,Late Night",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":64,\""android\"":16}""",False,POLYGON,...,NaN,900 Boylston St,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":80}""","""{\""250250106001\"":36,\""250250107011\"":9,\""250...","""{\""25025010600\"":38,\""25025010701\"":12,\""2502...","""{\""250250106001\"":38,\""250250107011\"":12,\""25...","""[2,3,3,4,4,3,4,3,2,2,4,2,2,2,3,5,3,3,3,3,2,4,...",65.0
13504,Regina Pizzeria,"""{ \""<5\"":135, \""5-20\"":6, \""21-60\"":27, \""61-...","Casual Dining,Catering,Dinner,Drinks,Italian F...",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":84,\""ios\"":63}""",False,POLYGON,...,NaN,11 1/2 Thacher St,Full-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":147}""","""{\""250250301002\"":49,\""250250302001\"":38,\""25...","""{\""25025030100\"":42,\""25025030200\"":37,\""2502...","""{\""250250301002\"":42,\""250250302001\"":37,\""25...","""[5,5,4,0,5,9,6,6,5,5,5,4,3,18,7,5,7,3,4,8,4,4...",77.0
13506,Bonchon,"""{ \""<5\"":194, \""5-20\"":15, \""21-60\"":13, \""61...","Casual Dining,Dinner,Fried Chicken,Fusion Food...",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":144,\""ios\"":38}""",False,POLYGON,...,1029,123 Brighton Ave,Limited-Service Restaurants,Restaurants and Other Eating Places,"""{\""US\"":182}""","""{\""250250008022\"":62,\""250214151023\"":31,\""25...","""{\""25025000802\"":55,\""25021415102\"":53,\""2500...","""{\""250214151023\"":53,\""250250008022\"":32,\""25...","""[10,8,6,7,7,5,12,9,7,7,6,6,6,6,10,8,8,6,6,7,7...",843.0
13507,NaN,"""{ \""<5\"":531, \""5-20\"":64, \""21-60\"":23, \""61...","Burgers,Dessert,Ice Cream Shop",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":414,\""android\"":203}""",True,POLYGON,...,NaN,254 S Market St,Snack and Nonalcoholic Beverage Bars,Restaurants and Other Eating Places,"""{\""US\"":617}""","""{\""250250303003\"":99,\""250250303002\"":38,\""25...","""{\""25025030300\"":92,\""25025070101\"":58,\""2502...","""{\""250250303003\"":64,\""250250203011\"":22,\""25...","""[26,8,13,10,6,13,8,12,43,43,12,14,12,15,58,66...",808.0

In [29]:
import json
import ast
import pandas as pd

def parse_bucketed_dwell(x):
    if pd.isna(x):
        return None

    # 1st attempt: JSON load once
    try:
        obj = json.loads(x)
    except Exception:
        obj = x

    # If we got a dict already → done
    if isinstance(obj, dict):
        return obj

    # If we got a string that still looks like JSON → try loading again
    if isinstance(obj, str):
        s = obj.strip()
        # Try JSON again
        try:
            obj2 = json.loads(s)
            if isinstance(obj2, dict):
                return obj2
        except Exception:
            pass
        # Try Python-style dict (single quotes, etc.)
        try:
            obj2 = ast.literal_eval(s)
            if isinstance(obj2, dict):
                return obj2
        except Exception:
            pass

    return None

In [22]:
df_rest["BUCKETED_DWELL_DICT"] = df_rest["BUCKETED_DWELL_TIMES"].apply(parse_bucketed_dwell)

In [23]:
all_buckets = set()
for d in df_rest["BUCKETED_DWELL_DICT"]:
    if isinstance(d, dict):
        all_buckets.update(d.keys())

print(all_buckets)

{'5-20', '<5', '61-240', '>240', '21-60'}

In [24]:
dwell_buckets = list(all_buckets)

for bucket in dwell_buckets:
    col_name = "dwell_" + bucket.replace("<", "lt").replace(">", "gt").replace("-", "_").replace("+", "plus")
    df_rest[col_name] = df_rest["BUCKETED_DWELL_DICT"].apply(
        lambda d: d.get(bucket, 0) if isinstance(d, dict) else 0
    )

dwell_cols = [c for c in df_rest.columns if c.startswith("dwell_")]
df_rest["dwell_total_obs"] = df_rest[dwell_cols].sum(axis=1)

In [25]:
df_rest

,BRANDS,BUCKETED_DWELL_TIMES,CATEGORY_TAGS,CITY,CLOSED_ON,DATE_RANGE_END,DATE_RANGE_START,DEVICE_TYPE,ENCLOSED,GEOMETRY_TYPE,...,VISITOR_HOME_CBGS,VISITS_BY_DAY,WKT_AREA_SQ_METERS,BUCKETED_DWELL_DICT,dwell_5_20,dwell_lt5,dwell_61_240,dwell_gt240,dwell_21_60,dwell_total_obs
93,NaN,"""{ \""<5\"":0, \""5-20\"":0, \""21-60\"":0, \""61-240...","Asian Food,Salad,Seafood,Vietnamese Food",Boston,NaT,2025-04-01,2025-03-01,NaN,False,POLYGON,...,NaN,"""[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,...",391.0,"{'<5': 0, '5-20': 0, '21-60': 0, '61-240': 0, ...",0,0,0,0,0,0
94,NaN,"""{ \""<5\"":184, \""5-20\"":13, \""21-60\"":10, \""61...",Sandwich Shop,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":85,\""ios\"":53}""",False,POLYGON,...,"""{\""250250404012\"":48,\""250250404011\"":21,\""25...","""[9,7,8,9,9,6,9,9,7,7,8,8,8,8,7,8,9,7,4,15,10,...",1010.0,"{'<5': 184, '5-20': 13, '21-60': 10, '61-240':...",13,184,26,20,10,253
95,NaN,"""{ \""<5\"":163, \""5-20\"":6, \""21-60\"":8, \""61-2...",Chinese Food,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":102,\""ios\"":43}""",False,POLYGON,...,"""{\""250250007031\"":61,\""250250007043\"":8,\""250...","""[6,6,6,6,9,7,7,5,6,6,6,7,8,7,10,14,5,8,6,7,7,...",1662.0,"{'<5': 163, '5-20': 6, '21-60': 8, '61-240': 1...",6,163,10,19,8,206
96,NaN,"""{ \""<5\"":1200, \""5-20\"":30, \""21-60\"":23, \""6...",Seafood,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":857,\""ios\"":71}""",True,POLYGON,...,"""{\""250250008031\"":155,\""250259813002\"":12,\""2...","""[44,29,24,43,46,36,49,52,44,44,31,40,38,44,61...",5397.0,"{'<5': 1200, '5-20': 30, '21-60': 23, '61-240'...",30,1200,35,92,23,1380
97,NaN,"""{ \""<5\"":66, \""5-20\"":25, \""21-60\"":28, \""61-...",Cafe,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":51,\""ios\"":32}""",True,POLYGON,...,"""{\""250250106001\"":62,\""371830537223\"":4,\""250...","""[5,5,6,7,7,6,5,5,5,5,6,5,4,6,6,4,6,6,3,6,3,3,...",146.0,"{'<5': 66, '5-20': 25, '21-60': 28, '61-240': ...",25,66,25,11,28,155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,Dunkin',"""{ \""<5\"":257, \""5-20\"":7, \""21-60\"":8, \""61-2...","Coffee Shop,Counter Service,Dessert,Donut Shop...",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":183,\""android\"":34}""",False,POLYGON,...,"""{\""250250305002\"":94,\""250259813002\"":23,\""51...","""[12,14,14,15,14,12,12,12,14,14,10,12,13,15,17...",956.0,"{'<5': 257, '5-20': 7, '21-60': 8, '61-240': 2...",7,257,28,113,8,413
13503,NaN,"""{ \""<5\"":90, \""5-20\"":0, \""21-60\"":0, \""61-24...","Bar or Pub,French Food,Late Night",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":64,\""android\"":16}""",False,POLYGON,...,"""{\""250250106001\"":38,\""250250107011\"":12,\""25...","""[2,3,3,4,4,3,4,3,2,2,4,2,2,2,3,5,3,3,3,3,2,4,...",65.0,"{'<5': 90, '5-20': 0, '21-60': 0, '61-240': 2,...",0,90,2,4,0,96
13504,Regina Pizzeria,"""{ \""<5\"":135, \""5-20\"":6, \""21-60\"":27, \""61-...","Casual Dining,Catering,Dinner,Drinks,Italian F...",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":84,\""ios\"":63}""",False,POLYGON,...,"""{\""250250301002\"":42,\""250250302001\"":37,\""25...","""[5,5,4,0,5,9,6,6,5,5,5,4,3,18,7,5,7,3,4,8,4,4...",77.0,"{'<5': 135, '5-20': 6, '21-60': 27, '61-240': ...",6,135,3,3,27,174
13506,Bonchon,"""{ \""<5\"":194, \""5-20\"":15, \""21-60\"":13, \""61...","Casual Dining,Dinner,Fried Chicken,Fusion Food...",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":144,\""ios\"":38}""",False,POLYGON,...,"""{\""250214151023\"":53,\""250250008022\"":32,\""25...","""[10,8,6,7,7,5,12,9,7,7,6,6,6,6,10,8,8,6,6,7,7...",843.0,"{'<5': 194, '5-20': 15, '21-60': 13, '61-240':...",15,194,8,2,13,232
13507,NaN,"""{ \""<5\"":531, \""5-20\"":64, \""21-60\"":23, \""61...","Burgers,Dessert,Ice Cream Shop",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":414,\""android\"":203}""",True,POLYGON,...,"""{\""250250303003\"":64,\""250250203011\"":22,\""25...","""[26,8,13,10,6,13,8,12,43,43,12,14,12,15,58,66...",808.0,"{'<5': 531, '5-20': 64, '21-60': 23, '61-240':...",64,531,35,2,23,655

In [30]:
# Parse POPULARITY_BY_DAY into a dict
df_rest["POP_DAY_DICT"] = df_rest["POPULARITY_BY_DAY"].apply(safe_json_load)

weekday_order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
pop_day_cols = []

for day in weekday_order:
    col_name = f"pop_{day.lower()}"
    pop_day_cols.append(col_name)
    df_rest[col_name] = df_rest["POP_DAY_DICT"].apply(
        lambda d: d.get(day, 0) if isinstance(d, dict) else 0
    )

# Convert to shares (each row: day_value / sum_of_all_days)
row_sum = df_rest[pop_day_cols].sum(axis=1).replace(0, np.nan)

for col in pop_day_cols:
    share_col = col + "_share"
    df_rest[share_col] = df_rest[col] / row_sum

NameError: name 'safe_json_load' is not defined

In [27]:
df_rest.tail()

,BRANDS,BUCKETED_DWELL_TIMES,CATEGORY_TAGS,CITY,CLOSED_ON,DATE_RANGE_END,DATE_RANGE_START,DEVICE_TYPE,ENCLOSED,GEOMETRY_TYPE,...,VISITOR_HOME_CBGS,VISITS_BY_DAY,WKT_AREA_SQ_METERS,BUCKETED_DWELL_DICT,dwell_5_20,dwell_lt5,dwell_61_240,dwell_gt240,dwell_21_60,dwell_total_obs
13437,Dunkin',"""{ \""<5\"":257, \""5-20\"":7, \""21-60\"":8, \""61-2...","Coffee Shop,Counter Service,Dessert,Donut Shop...",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":183,\""android\"":34}""",False,POLYGON,...,"""{\""250250305002\"":94,\""250259813002\"":23,\""51...","""[12,14,14,15,14,12,12,12,14,14,10,12,13,15,17...",956.0,"{'<5': 257, '5-20': 7, '21-60': 8, '61-240': 2...",7,257,28,113,8,413
13503,NaN,"""{ \""<5\"":90, \""5-20\"":0, \""21-60\"":0, \""61-24...","Bar or Pub,French Food,Late Night",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":64,\""android\"":16}""",False,POLYGON,...,"""{\""250250106001\"":38,\""250250107011\"":12,\""25...","""[2,3,3,4,4,3,4,3,2,2,4,2,2,2,3,5,3,3,3,3,2,4,...",65.0,"{'<5': 90, '5-20': 0, '21-60': 0, '61-240': 2,...",0,90,2,4,0,96
13504,Regina Pizzeria,"""{ \""<5\"":135, \""5-20\"":6, \""21-60\"":27, \""61-...","Casual Dining,Catering,Dinner,Drinks,Italian F...",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":84,\""ios\"":63}""",False,POLYGON,...,"""{\""250250301002\"":42,\""250250302001\"":37,\""25...","""[5,5,4,0,5,9,6,6,5,5,5,4,3,18,7,5,7,3,4,8,4,4...",77.0,"{'<5': 135, '5-20': 6, '21-60': 27, '61-240': ...",6,135,3,3,27,174
13506,Bonchon,"""{ \""<5\"":194, \""5-20\"":15, \""21-60\"":13, \""61...","Casual Dining,Dinner,Fried Chicken,Fusion Food...",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":144,\""ios\"":38}""",False,POLYGON,...,"""{\""250214151023\"":53,\""250250008022\"":32,\""25...","""[10,8,6,7,7,5,12,9,7,7,6,6,6,6,10,8,8,6,6,7,7...",843.0,"{'<5': 194, '5-20': 15, '21-60': 13, '61-240':...",15,194,8,2,13,232
13507,NaN,"""{ \""<5\"":531, \""5-20\"":64, \""21-60\"":23, \""61...","Burgers,Dessert,Ice Cream Shop",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":414,\""android\"":203}""",True,POLYGON,...,"""{\""250250303003\"":64,\""250250203011\"":22,\""25...","""[26,8,13,10,6,13,8,12,43,43,12,14,12,15,58,66...",808.0,"{'<5': 531, '5-20': 64, '21-60': 23, '61-240':...",64,531,35,2,23,655

In [31]:
def parse_popularity_day(x):
    if pd.isna(x):
        return None

    # First attempt: JSON once
    try:
        obj = json.loads(x)
    except Exception:
        obj = x

    # If it's already a dict, great
    if isinstance(obj, dict):
        return obj

    # If it's still a string, try again
    if isinstance(obj, str):
        s = obj.strip()
        # Try JSON again
        try:
            obj2 = json.loads(s)
            if isinstance(obj2, dict):
                return obj2
        except Exception:
            pass
        # Try Python-style dict
        try:
            obj2 = ast.literal_eval(s)
            if isinstance(obj2, dict):
                return obj2
        except Exception:
            pass

    return None

In [32]:
df_rest["POP_DAY_DICT"] = df_rest["POPULARITY_BY_DAY"].apply(parse_popularity_day)

In [33]:
df_rest["POP_DAY_DICT"].head()

93    {'Monday': 0, 'Tuesday': 1, 'Wednesday': 0, 'T...
94    {'Monday': 40, 'Tuesday': 27, 'Wednesday': 40,...
95    {'Monday': 31, 'Tuesday': 24, 'Wednesday': 29,...
96    {'Monday': 169, 'Tuesday': 153, 'Wednesday': 1...
97    {'Monday': 29, 'Tuesday': 19, 'Wednesday': 21,...
Name: POP_DAY_DICT, dtype: object

In [34]:
weekday_order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
pop_day_cols = []

for day in weekday_order:
    col_name = f"pop_{day.lower()}"
    pop_day_cols.append(col_name)
    df_rest[col_name] = df_rest["POP_DAY_DICT"].apply(
        lambda d: d.get(day, 0) if isinstance(d, dict) else 0
    )

# Row-wise sum of all weekdays
row_sum = df_rest[pop_day_cols].sum(axis=1).replace(0, np.nan)

for col in pop_day_cols:
    share_col = col + "_share"
    df_rest[share_col] = df_rest[col] / row_sum

NameError: name 'np' is not defined

In [35]:
df_rest

,BRANDS,BUCKETED_DWELL_TIMES,CATEGORY_TAGS,CITY,CLOSED_ON,DATE_RANGE_END,DATE_RANGE_START,DEVICE_TYPE,ENCLOSED,GEOMETRY_TYPE,...,dwell_21_60,dwell_total_obs,POP_DAY_DICT,pop_monday,pop_tuesday,pop_wednesday,pop_thursday,pop_friday,pop_saturday,pop_sunday
93,NaN,"""{ \""<5\"":0, \""5-20\"":0, \""21-60\"":0, \""61-240...","Asian Food,Salad,Seafood,Vietnamese Food",Boston,NaT,2025-04-01,2025-03-01,NaN,False,POLYGON,...,0,0,"{'Monday': 0, 'Tuesday': 1, 'Wednesday': 0, 'T...",0,1,0,0,0,0,0
94,NaN,"""{ \""<5\"":184, \""5-20\"":13, \""21-60\"":10, \""61...",Sandwich Shop,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":85,\""ios\"":53}""",False,POLYGON,...,10,253,"{'Monday': 40, 'Tuesday': 27, 'Wednesday': 40,...",40,27,40,29,32,49,38
95,NaN,"""{ \""<5\"":163, \""5-20\"":6, \""21-60\"":8, \""61-2...",Chinese Food,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":102,\""ios\"":43}""",False,POLYGON,...,8,206,"{'Monday': 31, 'Tuesday': 24, 'Wednesday': 29,...",31,24,29,27,30,39,29
96,NaN,"""{ \""<5\"":1200, \""5-20\"":30, \""21-60\"":23, \""6...",Seafood,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":857,\""ios\"":71}""",True,POLYGON,...,23,1380,"{'Monday': 169, 'Tuesday': 153, 'Wednesday': 1...",169,153,167,166,234,273,221
97,NaN,"""{ \""<5\"":66, \""5-20\"":25, \""21-60\"":28, \""61-...",Cafe,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":51,\""ios\"":32}""",True,POLYGON,...,28,155,"{'Monday': 29, 'Tuesday': 19, 'Wednesday': 21,...",29,19,21,19,20,25,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,Dunkin',"""{ \""<5\"":257, \""5-20\"":7, \""21-60\"":8, \""61-2...","Coffee Shop,Counter Service,Dessert,Donut Shop...",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":183,\""android\"":34}""",False,POLYGON,...,8,413,"{'Monday': 62, 'Tuesday': 53, 'Wednesday': 56,...",62,53,56,51,58,69,66
13503,NaN,"""{ \""<5\"":90, \""5-20\"":0, \""21-60\"":0, \""61-24...","Bar or Pub,French Food,Late Night",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":64,\""android\"":16}""",False,POLYGON,...,0,96,"{'Monday': 17, 'Tuesday': 11, 'Wednesday': 12,...",17,11,12,10,14,17,15
13504,Regina Pizzeria,"""{ \""<5\"":135, \""5-20\"":6, \""21-60\"":27, \""61-...","Casual Dining,Catering,Dinner,Drinks,Italian F...",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":84,\""ios\"":63}""",False,POLYGON,...,27,174,"{'Monday': 18, 'Tuesday': 11, 'Wednesday': 21,...",18,11,21,35,23,37,29
13506,Bonchon,"""{ \""<5\"":194, \""5-20\"":15, \""21-60\"":13, \""61...","Casual Dining,Dinner,Fried Chicken,Fusion Food...",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":144,\""ios\"":38}""",False,POLYGON,...,13,232,"{'Monday': 33, 'Tuesday': 26, 'Wednesday': 27,...",33,26,27,25,37,46,40
13507,NaN,"""{ \""<5\"":531, \""5-20\"":64, \""21-60\"":23, \""61...","Burgers,Dessert,Ice Cream Shop",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":414,\""android\"":203}""",True,POLYGON,...,23,655,"{'Monday': 86, 'Tuesday': 64, 'Wednesday': 61,...",86,64,61,56,102,186,103

In [36]:
df_rest["POP_HOUR_LIST"].apply(type).value_counts()

KeyError: 'POP_HOUR_LIST'

In [37]:
df_rest["POPULARITY_BY_HOUR"].iloc[0]
df_rest["POP_HOUR_LIST"].iloc[0]

KeyError: 'POP_HOUR_LIST'

In [72]:
import ast

def force_list_parse(x):
    try:
        return ast.literal_eval(x) if isinstance(x, str) else x
    except:
        return None

df_rest["POP_HOUR_LIST"] = df_rest["POPULARITY_BY_HOUR"].apply(force_list_parse)

In [38]:
df_rest["POP_HOUR_LIST"].apply(type).value_counts()

KeyError: 'POP_HOUR_LIST'

In [74]:
print(repr(df_rest["POPULARITY_BY_HOUR"].iloc[0]))

'"[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0]"'

In [39]:
import json

def parse_pop_hours(x):
    # Already a list? keep it
    if isinstance(x, list):
        return x
    
    if not isinstance(x, str):
        return None
    
    s = x
    
    # Try up to 2 JSON decodes to handle the double-encoded case
    for _ in range(2):
        try:
            s = json.loads(s)
        except json.JSONDecodeError:
            break
    
    # If after decoding we have a list, return it
    if isinstance(s, list):
        return s
    
    return None

df_rest["POP_HOUR_LIST"] = df_rest["POPULARITY_BY_HOUR"].apply(parse_pop_hours)

In [76]:
df_rest["POP_HOUR_LIST"].apply(type).value_counts()

<class 'list'>    858
Name: POP_HOUR_LIST, dtype: int64

In [40]:
import numpy as np

def get_peak_hour(lst):
    if isinstance(lst, list) and len(lst) == 24:
        return int(np.argmax(lst))
    return np.nan

def evening_share(lst):
    if not (isinstance(lst, list) and len(lst) == 24):
        return np.nan
    total = sum(lst)
    if total == 0:
        return 0
    # hours 17–22 (17,18,19,20,21,22)
    return sum(lst[17:23]) / total

df_rest["peak_hour"] = df_rest["POP_HOUR_LIST"].apply(get_peak_hour)
df_rest["evening_share"] = df_rest["POP_HOUR_LIST"].apply(evening_share)

In [41]:
df_rest[["POP_HOUR_LIST", "peak_hour", "evening_share"]].head(10)

,POP_HOUR_LIST,peak_hour,evening_share
93,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",15,0.000000
94,"[13, 5, 5, 5, 5, 5, 5, 18, 15, 25, 27, 26, 42,...",18,0.300948
95,"[16, 21, 19, 9, 9, 17, 37, 13, 23, 19, 19, 10,...",18,0.303983
96,"[43, 29, 43, 37, 45, 64, 98, 124, 138, 108, 13...",17,0.272109
97,"[8, 4, 0, 0, 0, 1, 0, 4, 4, 11, 7, 37, 8, 36, ...",15,0.058296
98,"[18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 26, 1...",10,0.247826
99,"[217, 185, 205, 212, 231, 315, 355, 304, 304, ...",13,0.244280
110,"[0, 0, 0, 0, 0, 0, 0, 0, 10, 19, 0, 0, 0, 42, ...",19,0.477612
111,"[177, 165, 131, 74, 55, 50, 178, 336, 314, 339...",10,0.265676
113,"[17, 20, 20, 18, 20, 24, 24, 16, 18, 18, 23, 2...",18,0.336576

In [42]:
def parse_visits_by_day(x):
    if pd.isna(x):
        return None

    # First attempt: JSON once
    try:
        obj = json.loads(x)
    except Exception:
        obj = x

    # If we already have a list → good
    if isinstance(obj, list):
        return obj

    # If we got a dict (rare, but just in case) → use its values
    if isinstance(obj, dict):
        return list(obj.values())

    # If it's still a string, try again
    if isinstance(obj, str):
        s = obj.strip()
        # Try JSON again
        try:
            obj2 = json.loads(s)
            if isinstance(obj2, list):
                return obj2
            if isinstance(obj2, dict):
                return list(obj2.values())
        except Exception:
            pass
        # Try Python-style literal (single quotes, etc.)
        try:
            obj2 = ast.literal_eval(s)
            if isinstance(obj2, list):
                return obj2
            if isinstance(obj2, dict):
                return list(obj2.values())
        except Exception:
            pass

    return None

In [43]:
df_rest["VISITS_BY_DAY_LIST"] = df_rest["VISITS_BY_DAY"].apply(parse_visits_by_day)

In [44]:
def safe_avg(lst):
    if isinstance(lst, list) and len(lst) > 0:
        return float(np.mean(lst))
    return np.nan

def safe_max(lst):
    if isinstance(lst, list) and len(lst) > 0:
        return float(np.max(lst))
    return np.nan

def safe_std(lst):
    if isinstance(lst, list) and len(lst) > 1:
        return float(np.std(lst))
    return np.nan

df_rest["avg_daily_visits"] = df_rest["VISITS_BY_DAY_LIST"].apply(safe_avg)
df_rest["max_daily_visits"] = df_rest["VISITS_BY_DAY_LIST"].apply(safe_max)
df_rest["std_daily_visits"] = df_rest["VISITS_BY_DAY_LIST"].apply(safe_std)

In [88]:
df_rest

,BRANDS,BUCKETED_DWELL_TIMES,CATEGORY_TAGS,CITY,CLOSED_ON,DATE_RANGE_END,DATE_RANGE_START,DEVICE_TYPE,ENCLOSED,GEOMETRY_TYPE,...,pop_friday_share,pop_saturday_share,pop_sunday_share,POP_HOUR_LIST,peak_hour,evening_share,VISITS_BY_DAY_LIST,avg_daily_visits,max_daily_visits,std_daily_visits
93,NaN,"""{ \""<5\"":0, \""5-20\"":0, \""21-60\"":0, \""61-240...","Asian Food,Salad,Seafood,Vietnamese Food",Boston,NaT,2025-04-01,2025-03-01,NaN,False,POLYGON,...,0.000000,0.000000,0.000000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",15,0.000000,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.032258,1.0,0.176685
94,NaN,"""{ \""<5\"":184, \""5-20\"":13, \""21-60\"":10, \""61...",Sandwich Shop,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":85,\""ios\"":53}""",False,POLYGON,...,0.125490,0.192157,0.149020,"[13, 5, 5, 5, 5, 5, 5, 18, 15, 25, 27, 26, 42,...",18,0.300948,"[9, 7, 8, 9, 9, 6, 9, 9, 7, 7, 8, 8, 8, 8, 7, ...",8.161290,15.0,2.049339
95,NaN,"""{ \""<5\"":163, \""5-20\"":6, \""21-60\"":8, \""61-2...",Chinese Food,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":102,\""ios\"":43}""",False,POLYGON,...,0.143541,0.186603,0.138756,"[16, 21, 19, 9, 9, 17, 37, 13, 23, 19, 19, 10,...",18,0.303983,"[6, 6, 6, 6, 9, 7, 7, 5, 6, 6, 6, 7, 8, 7, 10,...",6.741935,14.0,1.865955
96,NaN,"""{ \""<5\"":1200, \""5-20\"":30, \""21-60\"":23, \""6...",Seafood,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":857,\""ios\"":71}""",True,POLYGON,...,0.169197,0.197397,0.159798,"[43, 29, 43, 37, 45, 64, 98, 124, 138, 108, 13...",17,0.272109,"[44, 29, 24, 43, 46, 36, 49, 52, 44, 44, 31, 4...",44.483871,75.0,11.074152
97,NaN,"""{ \""<5\"":66, \""5-20\"":25, \""21-60\"":28, \""61-...",Cafe,Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":51,\""ios\"":32}""",True,POLYGON,...,0.126582,0.158228,0.158228,"[8, 4, 0, 0, 0, 1, 0, 4, 4, 11, 7, 37, 8, 36, ...",15,0.058296,"[5, 5, 6, 7, 7, 6, 5, 5, 5, 5, 6, 5, 4, 6, 6, ...",5.032258,7.0,1.092020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,Dunkin',"""{ \""<5\"":257, \""5-20\"":7, \""21-60\"":8, \""61-2...","Coffee Shop,Counter Service,Dessert,Donut Shop...",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":183,\""android\"":34}""",False,POLYGON,...,0.139759,0.166265,0.159036,"[19, 14, 21, 24, 25, 27, 31, 37, 35, 48, 16, 3...",18,0.410050,"[12, 14, 14, 15, 14, 12, 12, 12, 14, 14, 10, 1...",13.322581,20.0,2.305493
13503,NaN,"""{ \""<5\"":90, \""5-20\"":0, \""21-60\"":0, \""61-24...","Bar or Pub,French Food,Late Night",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":64,\""android\"":16}""",False,POLYGON,...,0.145833,0.177083,0.156250,"[3, 0, 0, 0, 0, 0, 3, 0, 3, 2, 7, 3, 28, 37, 1...",13,0.176056,"[2, 3, 3, 4, 4, 3, 4, 3, 2, 2, 4, 2, 2, 2, 3, ...",3.032258,5.0,0.782216
13504,Regina Pizzeria,"""{ \""<5\"":135, \""5-20\"":6, \""21-60\"":27, \""61-...","Casual Dining,Catering,Dinner,Drinks,Italian F...",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":84,\""ios\"":63}""",False,POLYGON,...,0.132184,0.212644,0.166667,"[10, 6, 0, 0, 0, 0, 0, 0, 0, 4, 18, 17, 13, 35...",13,0.320346,"[5, 5, 4, 0, 5, 9, 6, 6, 5, 5, 5, 4, 3, 18, 7,...",5.580645,18.0,3.643591
13506,Bonchon,"""{ \""<5\"":194, \""5-20\"":15, \""21-60\"":13, \""61...","Casual Dining,Dinner,Fried Chicken,Fusion Food...",Boston,NaT,2025-04-01,2025-03-01,"""{\""android\"":144,\""ios\"":38}""",False,POLYGON,...,0.158120,0.196581,0.170940,"[1, 7, 13, 1, 5, 0, 0, 9, 15, 7, 21, 33, 18, 9...",14,0.376176,"[10, 8, 6, 7, 7, 5, 12, 9, 7, 7, 6, 6, 6, 6, 1...",7.516129,12.0,1.563102
13507,NaN,"""{ \""<5\"":531, \""5-20\"":64, \""21-60\"":23, \""61...","Burgers,Dessert,Ice Cream Shop",Boston,NaT,2025-04-01,2025-03-01,"""{\""ios\"":414,\""android\"":203}""",True,POLYGON,...,0.155015,0.282675,0.156535,"[0, 0, 0, 0, 0, 0, 0, 1, 3, 5, 19, 115, 95, 11...",11,0.198693,"[26, 8, 13, 10, 6, 13, 8, 12, 43, 43, 12, 14, ...",22.290323,66.0,15.379487

In [45]:
df_rest.shape

(858, 72)

In [46]:
df_rest.to_csv("df_rest_cleaned.csv", index=False)

In [47]:
df_rest.isnull().sum().head(20)

BRANDS                                        704
BUCKETED_DWELL_TIMES                            0
CATEGORY_TAGS                                  51
CITY                                            0
CLOSED_ON                                     858
DATE_RANGE_END                                  0
DATE_RANGE_START                                0
DEVICE_TYPE                                    23
ENCLOSED                                        0
GEOMETRY_TYPE                                   0
INCLUDES_PARKING_LOT                           16
ISO_COUNTRY_CODE                                0
IS_SYNTHETIC                                    0
LATITUDE                                        0
LOCATION_NAME                                   0
LONGITUDE                                       0
MEDIAN_DWELL                                    0
NAICS_CODE                                      0
NORMALIZED_VISITS_BY_REGION_NAICS_VISITORS      0
NORMALIZED_VISITS_BY_REGION_NAICS_VISITS        0
dtype: int64

In [48]:
cols_to_drop = [
    # Raw JSON columns
    "BUCKETED_DWELL_TIMES", "POPULARITY_BY_DAY", "POPULARITY_BY_HOUR",
    "VISITS_BY_DAY", "VISITOR_HOME_CBGS", "VISITOR_DAYTIME_CBGS",

    # Parsed helper dictionaries/lists
    "BUCKETED_DWELL_DICT", "POP_DAY_DICT", "POP_HOUR_LIST", "VISITS_BY_DAY_LIST",

    # Raw daily/hourly values (duplicates)
    "pop_monday", "pop_tuesday", "pop_wednesday", "pop_thursday",
    "pop_friday", "pop_saturday", "pop_sunday",

    # Geometry / spatial WKT data
    "POLYGON_WKT", "WKT_AREA_SQ_METERS", "GEOMETRY_TYPE",

    # Dates (no longer needed)
    "DATE_RANGE_START", "DATE_RANGE_END", "OPENED_ON", "CLOSED_ON",
]

In [49]:
df_rest = df_rest.drop(columns=[col for col in cols_to_drop if col in df_rest.columns])

In [50]:
df_rest

,BRANDS,CATEGORY_TAGS,CITY,DEVICE_TYPE,ENCLOSED,INCLUDES_PARKING_LOT,ISO_COUNTRY_CODE,IS_SYNTHETIC,LATITUDE,LOCATION_NAME,...,dwell_lt5,dwell_61_240,dwell_gt240,dwell_21_60,dwell_total_obs,peak_hour,evening_share,avg_daily_visits,max_daily_visits,std_daily_visits
93,NaN,"Asian Food,Salad,Seafood,Vietnamese Food",Boston,NaN,False,False,US,False,42.299857,Huong Que,...,0,0,0,0,0,15,0.000000,0.032258,1.0,0.176685
94,NaN,Sandwich Shop,Boston,"""{\""android\"":85,\""ios\"":53}""",False,False,US,False,42.376386,Puxadinho,...,184,26,20,10,253,18,0.300948,8.161290,15.0,2.049339
95,NaN,Chinese Food,Boston,"""{\""android\"":102,\""ios\"":43}""",False,False,US,False,42.349960,Bos Sichuan Taste,...,163,10,19,8,206,18,0.303983,6.741935,14.0,1.865955
96,NaN,Seafood,Boston,"""{\""android\"":857,\""ios\"":71}""",True,False,US,False,42.360112,Boathouse 400,...,1200,35,92,23,1380,17,0.272109,44.483871,75.0,11.074152
97,NaN,Cafe,Boston,"""{\""android\"":51,\""ios\"":32}""",True,False,US,False,42.349251,Newsfeed Cafe,...,66,25,11,28,155,15,0.058296,5.032258,7.0,1.092020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13437,Dunkin',"Coffee Shop,Counter Service,Dessert,Donut Shop...",Boston,"""{\""ios\"":183,\""android\"":34}""",False,False,US,False,42.364766,Dunkin',...,257,28,113,8,413,18,0.410050,13.322581,20.0,2.305493
13503,NaN,"Bar or Pub,French Food,Late Night",Boston,"""{\""ios\"":64,\""android\"":16}""",False,False,US,False,42.348229,Rochambeau,...,90,2,4,0,96,13,0.176056,3.032258,5.0,0.782216
13504,Regina Pizzeria,"Casual Dining,Catering,Dinner,Drinks,Italian F...",Boston,"""{\""android\"":84,\""ios\"":63}""",False,False,US,False,42.365465,Regina Pizzeria,...,135,3,3,27,174,13,0.320346,5.580645,18.0,3.643591
13506,Bonchon,"Casual Dining,Dinner,Fried Chicken,Fusion Food...",Boston,"""{\""android\"":144,\""ios\"":38}""",False,False,US,False,42.353109,Bonchon,...,194,8,2,13,232,14,0.376176,7.516129,12.0,1.563102
13507,NaN,"Burgers,Dessert,Ice Cream Shop",Boston,"""{\""ios\"":414,\""android\"":203}""",True,False,US,False,42.360027,Quincy's Place,...,531,35,2,23,655,11,0.198693,22.290323,66.0,15.379487

In [51]:
df_rest.to_csv("df_rest_cleaned_new.csv", index=False)

In [52]:
cols_to_drop = [
    "DEVICE_TYPE",                               # iOS vs Android – not needed
    "ISO_COUNTRY_CODE",                         # always "US" here
    "IS_SYNTHETIC",                             # internal SafeGraph flag
    "NORMALIZED_VISITS_BY_REGION_NAICS_VISITORS",
    "NORMALIZED_VISITS_BY_REGION_NAICS_VISITS",
    "NORMALIZED_VISITS_BY_STATE_SCALING",       # extra scaling metrics, overkill
    "OPEN_HOURS",                               # messy/unstructured, hard to use now
    "PARENT_PLACEKEY",                          # mall nesting info, not essential
    "PHONE_NUMBER",                             # not needed
    "PLACEKEY",                                 # internal ID
    "POI_CBG",                                  # only needed if you join census data
    "POLYGON_CLASS",                            # geometry details
    "RELATED_SAME_DAY_BRAND",
    "RELATED_SAME_MONTH_BRAND",                 # brand co-visitation – not needed
    "SAFEGRAPH_BRAND_IDS",
    "STORE_ID",                                 # internal identifiers
    "VISITOR_COUNTRY_OF_ORIGIN",                # all US anyway
    "VISITOR_HOME_AGGREGATION",                 # advanced, not needed now
    "dwell_61_120",                             # all zeros in your data
    "dwell_gt120"                               # all zeros in your data
]

In [53]:
df_rest = df_rest.drop(columns=[c for c in cols_to_drop if c in df_rest.columns])

In [54]:
df_rest.to_csv("df_rest_final.csv", index=False)

In [55]:
df_rest.shape

(858, 30)

In [56]:
dwell_cols = ["dwell_lt5", "dwell_5_20", "dwell_21_60", "dwell_61_240", "dwell_gt240"]

# Avoid division by zero
df_rest["dwell_total_obs"] = df_rest[dwell_cols].sum(axis=1)
df_rest["dwell_total_obs"] = df_rest["dwell_total_obs"].replace(0, np.nan)

for col in dwell_cols:
    share_col = col + "_share"
    df_rest[share_col] = df_rest[col] / df_rest["dwell_total_obs"]

In [57]:
df_rest["fast_food_behavior_score"] = (
    0.6 * df_rest["dwell_lt5_share"].fillna(0) +
    0.4 * df_rest["dwell_5_20_share"].fillna(0)
)

In [58]:
df_rest["weekend_demand_score"] = (
    df_rest["pop_saturday_share"].fillna(0) +
    df_rest["pop_sunday_share"].fillna(0)
)

KeyError: 'pop_saturday_share'

In [59]:
weekday_share = (
    df_rest["pop_monday_share"].fillna(0) +
    df_rest["pop_tuesday_share"].fillna(0) +
    df_rest["pop_wednesday_share"].fillna(0) +
    df_rest["pop_thursday_share"].fillna(0) +
    df_rest["pop_friday_share"].fillna(0)
)

df_rest["weekday_daytime_score"] = weekday_share * (1 - df_rest["evening_share"].fillna(0))

KeyError: 'pop_monday_share'

In [60]:
def minmax(s):
    s = s.astype(float)
    min_v, max_v = s.min(), s.max()
    if pd.isna(min_v) or pd.isna(max_v) or max_v == min_v:
        return pd.Series(0.5, index=s.index)  # neutral if constant
    return (s - min_v) / (max_v - min_v)

In [61]:
df_rest["visit_volume_score"] = minmax(df_rest["RAW_VISIT_COUNTS"].fillna(0))

In [62]:
# First normalise std
std_norm = minmax(df_rest["std_daily_visits"].fillna(0))

# Stability = 1 - normalized volatility
df_rest["stability_score"] = 1 - std_norm

In [63]:
# Number of restaurant POIs per ZIP code
zip_counts = df_rest.groupby("POSTAL_CODE")["LOCATION_NAME"].count().rename("zip_restaurant_count")

df_rest = df_rest.merge(zip_counts, on="POSTAL_CODE", how="left")

In [64]:
density_norm = minmax(df_rest["zip_restaurant_count"])
df_rest["competition_score"] = 1 - density_norm

In [65]:
score_cols_to_norm = [
    "fast_food_behavior_score",
    "weekend_demand_score",
    "weekday_daytime_score",
    "visit_volume_score",
    "stability_score",
    "competition_score"
]

for col in score_cols_to_norm:
    df_rest[col + "_norm"] = minmax(df_rest[col].fillna(0))

KeyError: 'weekend_demand_score'

In [66]:
df_rest["restaurant_score"] = (
    0.25 * df_rest["fast_food_behavior_score_norm"] +
    0.25 * df_rest["visit_volume_score_norm"] +
    0.15 * df_rest["weekend_demand_score_norm"] +
    0.15 * df_rest["weekday_daytime_score_norm"] +
    0.10 * df_rest["stability_score_norm"] +
    0.10 * df_rest["competition_score_norm"]
)

KeyError: 'visit_volume_score_norm'

In [67]:
zip_agg = df_rest.groupby("POSTAL_CODE").agg({
    "restaurant_score": "mean",
    "visit_volume_score": "mean",
    "fast_food_behavior_score": "mean",
    "weekend_demand_score": "mean",
    "weekday_daytime_score": "mean",
    "stability_score": "mean",
    "competition_score": "mean",
    "LOCATION_NAME": "count"
}).rename(columns={"LOCATION_NAME": "restaurant_count"}).reset_index()

KeyError: "Column(s) ['restaurant_score', 'weekday_daytime_score', 'weekend_demand_score'] do not exist"

In [ ]:
zip_agg["zip_score"] = minmax(zip_agg["restaurant_score"])

In [68]:
zip_agg = zip_agg.sort_values("zip_score", ascending=False)

NameError: name 'zip_agg' is not defined

In [69]:
df_rest.to_csv("df_rest_scored.csv", index=False)
zip_agg.to_csv("df_zip_scores.csv", index=False)

NameError: name 'zip_agg' is not defined

In [70]:
df_rest[(df_rest['POSTAL_CODE'] == 2139.0) & df_rest['visit_volume_score']>0]

,BRANDS,CATEGORY_TAGS,CITY,ENCLOSED,INCLUDES_PARKING_LOT,LATITUDE,LOCATION_NAME,LONGITUDE,MEDIAN_DWELL,NAICS_CODE,...,dwell_5_20_share,dwell_21_60_share,dwell_61_240_share,dwell_gt240_share,fast_food_behavior_score,visit_volume_score,stability_score,zip_restaurant_count,competition_score,fast_food_behavior_score_norm
538,NaN,Chinese Food,Boston,False,False,42.36023,Megumi,-71.054021,2.0,722511,...,0.082949,0.066491,0.061224,0.008558,0.501646,0.035926,0.88903,1,1.0,0.836076

In [71]:
df_rest.loc[df_rest['POSTAL_CODE'] == 2139.0, 'visit_volume_score']

538    0.035926
Name: visit_volume_score, dtype: float64

In [75]:
df_rest

,BRANDS,CATEGORY_TAGS,CITY,ENCLOSED,INCLUDES_PARKING_LOT,LATITUDE,LOCATION_NAME,LONGITUDE,MEDIAN_DWELL,NAICS_CODE,...,dwell_5_20_share,dwell_21_60_share,dwell_61_240_share,dwell_gt240_share,fast_food_behavior_score,visit_volume_score,stability_score,zip_restaurant_count,competition_score,fast_food_behavior_score_norm
0,NaN,"Asian Food,Salad,Seafood,Vietnamese Food",Boston,False,False,42.299857,Huong Que,-71.058404,48.0,722511,...,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,9,0.901235,0.000000
1,NaN,Sandwich Shop,Boston,False,False,42.376386,Puxadinho,-71.065349,12.0,722511,...,0.051383,0.039526,0.102767,0.079051,0.456917,0.006003,0.991437,8,0.913580,0.761528
2,NaN,Chinese Food,Boston,False,False,42.349960,Bos Sichuan Taste,-71.130476,37.0,722511,...,0.029126,0.038835,0.048544,0.092233,0.486408,0.004916,0.992276,23,0.728395,0.810680
3,NaN,Seafood,Boston,True,False,42.360112,Boathouse 400,-71.118136,37.0,722511,...,0.021739,0.016667,0.025362,0.066667,0.530435,0.032664,0.950171,23,0.728395,0.884058
4,NaN,Cafe,Boston,True,False,42.349251,Newsfeed Cafe,-71.079076,35.0,722513,...,0.161290,0.180645,0.161290,0.070968,0.320000,0.003711,0.995815,81,0.012346,0.533333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,Dunkin',"Coffee Shop,Counter Service,Dessert,Donut Shop...",Boston,False,False,42.364766,Dunkin',-71.052626,296.0,722515,...,0.016949,0.019370,0.067797,0.273608,0.380145,0.009785,0.990266,40,0.518519,0.633575
854,NaN,"Bar or Pub,French Food,Late Night",Boston,False,False,42.348229,Rochambeau,-71.083554,2.0,722511,...,0.000000,0.000000,0.020833,0.041667,0.562500,0.002245,0.997231,75,0.086420,0.937500
855,Regina Pizzeria,"Casual Dining,Catering,Dinner,Drinks,Italian F...",Boston,False,False,42.365465,Regina Pizzeria,-71.056872,3.0,722511,...,0.034483,0.155172,0.017241,0.017241,0.479310,0.004089,0.984147,40,0.518519,0.798851
856,Bonchon,"Casual Dining,Dinner,Fried Chicken,Fusion Food...",Boston,False,False,42.353109,Bonchon,-71.130929,1.0,722513,...,0.064655,0.056034,0.034483,0.008621,0.527586,0.005507,0.993661,23,0.728395,0.879310
857,NaN,"Burgers,Dessert,Ice Cream Shop",Boston,True,False,42.360027,Quincy's Place,-71.056238,2.0,722515,...,0.097710,0.035115,0.053435,0.003053,0.525496,0.015529,0.930485,47,0.432099,0.875827

In [74]:
import statsmodels.api as sm
import pandas as pd
import numpy as np

In [77]:
# Dependent variable (what we want to explain)
y = df_rest["avg_daily_visits"]

In [79]:
# Independent variables (drivers of demand)
X = df_rest[
    [
        "fast_food_behavior_score",
        "evening_share",
        "competition_score",
        "stability_score"
    ]
]

In [80]:
data = pd.concat([y, X], axis=1).dropna()

y_clean = data["avg_daily_visits"]
X_clean = data.drop(columns=["avg_daily_visits"])

In [81]:
X_clean = sm.add_constant(X_clean)

In [82]:
model = sm.OLS(y_clean, X_clean)
results = model.fit()

In [83]:
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       avg_daily_visits   R-squared:                       0.775
Model:                            OLS   Adj. R-squared:                  0.774
Method:                 Least Squares   F-statistic:                     733.2
Date:                Fri, 12 Dec 2025   Prob (F-statistic):          3.07e-274
Time:                        20:23:29   Log-Likelihood:                -4264.5
No. Observations:                 858   AIC:                             8539.
Df Residuals:                     853   BIC:                             8563.
Df Model:                           4
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                      900.9136     16.649     54.111      0.000     868.235     933.592
fast_food_behavior_score     4.6814     11.752      0.398      0.690     -18.386      27.749
evening_share               -3.3468      8.854     -0.378      0.706     -20.725      14.032
competition_score           -1.4254      4.103     -0.347      0.728      -9.479       6.628
stability_score           -907.2365     17.116    -53.004      0.000    -940.832    -873.641
==============================================================================
Omnibus:                      939.937   Durbin-Watson:                   1.926
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           127446.373
Skew:                           4.959   Prob(JB):                         0.00
Kurtosis:                      61.878   Cond. No.                         30.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [84]:
data

,avg_daily_visits,fast_food_behavior_score,evening_share,competition_score,stability_score
0,0.032258,0.000000,0.000000,0.901235,1.000000
1,8.161290,0.456917,0.300948,0.913580,0.991437
2,6.741935,0.486408,0.303983,0.728395,0.992276
3,44.483871,0.530435,0.272109,0.728395,0.950171
4,5.032258,0.320000,0.058296,0.012346,0.995815
...,...,...,...,...,...
853,13.322581,0.380145,0.410050,0.518519,0.990266
854,3.032258,0.562500,0.176056,0.086420,0.997231
855,5.580645,0.479310,0.320346,0.518519,0.984147
856,7.516129,0.527586,0.376176,0.728395,0.993661
857,22.290323,0.525496,0.198693,0.432099,0.930485